### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [dirkz/NetHack-Cocoa#1]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [0.3.4 release files](https://code.google.com/p/nethack-cocoa/downloads/list) to somewhere else? (eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by dirkz** [comment]
Ah, there is a brew cask. Nice :) I moved the releases. Let me know if anything is off here. SHA-1 checksums (the same as mentioned on the google code page):

```
NetHack_releases$ shasum *
f10afee54e42e1f57f8578d2b08651f6efc8f70c  NetHackCocoa-0.3.4.dmg
5b135f83d58dd81b1c9c9ec5d4107c2f304307f4  SlashEMCocoa-0.1.dmg
```

**Comment by tsparber** [comment]
Thank you! 

Refs https://github.com/caskroom/homebrew-cask/pull/17327
